/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedWorkspaceSlugWelcomeImport } from './routes/_authenticated/$workspaceSlug/welcome'
import { Route as AuthenticatedWorkspaceSlugDashboardImport } from './routes/_authenticated/$workspaceSlug/_dashboard'
import { Route as AuthenticatedWorkspaceSlugDashboardIndexImport } from './routes/_authenticated/$workspaceSlug/_dashboard/index'
import { Route as AuthenticatedWorkspaceSlugDashboardGettingStartedImport } from './routes/_authenticated/$workspaceSlug/_dashboard/getting-started'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsIndexImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/index'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/index'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare'
import { Route as AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesImport } from './routes/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities'

// Create Virtual Routes

const AuthenticatedWorkspaceSlugImport = createFileRoute(
  '/_authenticated/$workspaceSlug',
)()

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedWorkspaceSlugRoute = AuthenticatedWorkspaceSlugImport.update(
  {
    id: '/$workspaceSlug',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const authSignupRoute = authSignupImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedWorkspaceSlugWelcomeRoute =
  AuthenticatedWorkspaceSlugWelcomeImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedWorkspaceSlugRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardRoute =
  AuthenticatedWorkspaceSlugDashboardImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedWorkspaceSlugRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardIndexRoute =
  AuthenticatedWorkspaceSlugDashboardIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceSlugDashboardRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardGettingStartedRoute =
  AuthenticatedWorkspaceSlugDashboardGettingStartedImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => AuthenticatedWorkspaceSlugDashboardRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedWorkspaceSlugDashboardRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AuthenticatedWorkspaceSlugDashboardRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () =>
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () =>
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute,
  } as any)

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesImport.update(
    {
      id: '/activities',
      path: '/activities',
      getParentRoute: () =>
        AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/$workspaceSlug': {
      id: '/_authenticated/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/$workspaceSlug/_dashboard': {
      id: '/_authenticated/$workspaceSlug/_dashboard'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardImport
      parentRoute: typeof AuthenticatedWorkspaceSlugRoute
    }
    '/_authenticated/$workspaceSlug/welcome': {
      id: '/_authenticated/$workspaceSlug/welcome'
      path: '/welcome'
      fullPath: '/$workspaceSlug/welcome'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugWelcomeImport
      parentRoute: typeof AuthenticatedWorkspaceSlugImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/getting-started': {
      id: '/_authenticated/$workspaceSlug/_dashboard/getting-started'
      path: '/getting-started'
      fullPath: '/$workspaceSlug/getting-started'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardGettingStartedImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/': {
      id: '/_authenticated/$workspaceSlug/_dashboard/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardIndexImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/$workspaceSlug/projects/$projectSlug'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/'
      path: '/projects'
      fullPath: '/$workspaceSlug/projects'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsIndexImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities'
      path: '/activities'
      fullPath: '/$workspaceSlug/projects/$projectSlug/activities'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare'
      path: '/compare'
      fullPath: '/$workspaceSlug/projects/$projectSlug/compare'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people'
      path: '/people'
      fullPath: '/$workspaceSlug/projects/$projectSlug/people'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport
    }
    '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/': {
      id: '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexImport
      parentRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteChildren {
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute
}

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteChildren: AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteChildren =
  {
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute,
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute,
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute,
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute,
  }

const AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteWithChildren =
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute._addFileChildren(
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteChildren,
  )

interface AuthenticatedWorkspaceSlugDashboardRouteChildren {
  AuthenticatedWorkspaceSlugDashboardGettingStartedRoute: typeof AuthenticatedWorkspaceSlugDashboardGettingStartedRoute
  AuthenticatedWorkspaceSlugDashboardIndexRoute: typeof AuthenticatedWorkspaceSlugDashboardIndexRoute
  AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteWithChildren
  AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute: typeof AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute
}

const AuthenticatedWorkspaceSlugDashboardRouteChildren: AuthenticatedWorkspaceSlugDashboardRouteChildren =
  {
    AuthenticatedWorkspaceSlugDashboardGettingStartedRoute:
      AuthenticatedWorkspaceSlugDashboardGettingStartedRoute,
    AuthenticatedWorkspaceSlugDashboardIndexRoute:
      AuthenticatedWorkspaceSlugDashboardIndexRoute,
    AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteWithChildren,
    AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute:
      AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute,
  }

const AuthenticatedWorkspaceSlugDashboardRouteWithChildren =
  AuthenticatedWorkspaceSlugDashboardRoute._addFileChildren(
    AuthenticatedWorkspaceSlugDashboardRouteChildren,
  )

interface AuthenticatedWorkspaceSlugRouteChildren {
  AuthenticatedWorkspaceSlugDashboardRoute: typeof AuthenticatedWorkspaceSlugDashboardRouteWithChildren
  AuthenticatedWorkspaceSlugWelcomeRoute: typeof AuthenticatedWorkspaceSlugWelcomeRoute
}

const AuthenticatedWorkspaceSlugRouteChildren: AuthenticatedWorkspaceSlugRouteChildren =
  {
    AuthenticatedWorkspaceSlugDashboardRoute:
      AuthenticatedWorkspaceSlugDashboardRouteWithChildren,
    AuthenticatedWorkspaceSlugWelcomeRoute:
      AuthenticatedWorkspaceSlugWelcomeRoute,
  }

const AuthenticatedWorkspaceSlugRouteWithChildren =
  AuthenticatedWorkspaceSlugRoute._addFileChildren(
    AuthenticatedWorkspaceSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceSlugRoute: typeof AuthenticatedWorkspaceSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceSlugRoute: AuthenticatedWorkspaceSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$workspaceSlug': typeof AuthenticatedWorkspaceSlugDashboardRouteWithChildren
  '/$workspaceSlug/welcome': typeof AuthenticatedWorkspaceSlugWelcomeRoute
  '/$workspaceSlug/getting-started': typeof AuthenticatedWorkspaceSlugDashboardGettingStartedRoute
  '/$workspaceSlug/': typeof AuthenticatedWorkspaceSlugDashboardIndexRoute
  '/$workspaceSlug/projects/$projectSlug': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteWithChildren
  '/$workspaceSlug/projects': typeof AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute
  '/$workspaceSlug/projects/$projectSlug/activities': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute
  '/$workspaceSlug/projects/$projectSlug/compare': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute
  '/$workspaceSlug/projects/$projectSlug/people': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute
  '/$workspaceSlug/projects/$projectSlug/': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$workspaceSlug': typeof AuthenticatedWorkspaceSlugDashboardIndexRoute
  '/$workspaceSlug/welcome': typeof AuthenticatedWorkspaceSlugWelcomeRoute
  '/$workspaceSlug/getting-started': typeof AuthenticatedWorkspaceSlugDashboardGettingStartedRoute
  '/$workspaceSlug/projects': typeof AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute
  '/$workspaceSlug/projects/$projectSlug/activities': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute
  '/$workspaceSlug/projects/$projectSlug/compare': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute
  '/$workspaceSlug/projects/$projectSlug/people': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute
  '/$workspaceSlug/projects/$projectSlug': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authenticated/$workspaceSlug': typeof AuthenticatedWorkspaceSlugRouteWithChildren
  '/_authenticated/$workspaceSlug/_dashboard': typeof AuthenticatedWorkspaceSlugDashboardRouteWithChildren
  '/_authenticated/$workspaceSlug/welcome': typeof AuthenticatedWorkspaceSlugWelcomeRoute
  '/_authenticated/$workspaceSlug/_dashboard/getting-started': typeof AuthenticatedWorkspaceSlugDashboardGettingStartedRoute
  '/_authenticated/$workspaceSlug/_dashboard/': typeof AuthenticatedWorkspaceSlugDashboardIndexRoute
  '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugRouteWithChildren
  '/_authenticated/$workspaceSlug/_dashboard/projects/': typeof AuthenticatedWorkspaceSlugDashboardProjectsIndexRoute
  '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugActivitiesRoute
  '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugCompareRoute
  '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugPeopleRoute
  '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/': typeof AuthenticatedWorkspaceSlugDashboardProjectsProjectSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$workspaceSlug'
    | '/$workspaceSlug/welcome'
    | '/$workspaceSlug/getting-started'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/projects/$projectSlug'
    | '/$workspaceSlug/projects'
    | '/$workspaceSlug/projects/$projectSlug/activities'
    | '/$workspaceSlug/projects/$projectSlug/compare'
    | '/$workspaceSlug/projects/$projectSlug/people'
    | '/$workspaceSlug/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$workspaceSlug'
    | '/$workspaceSlug/welcome'
    | '/$workspaceSlug/getting-started'
    | '/$workspaceSlug/projects'
    | '/$workspaceSlug/projects/$projectSlug/activities'
    | '/$workspaceSlug/projects/$projectSlug/compare'
    | '/$workspaceSlug/projects/$projectSlug/people'
    | '/$workspaceSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authenticated/$workspaceSlug'
    | '/_authenticated/$workspaceSlug/_dashboard'
    | '/_authenticated/$workspaceSlug/welcome'
    | '/_authenticated/$workspaceSlug/_dashboard/getting-started'
    | '/_authenticated/$workspaceSlug/_dashboard/'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people'
    | '/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth",
        "/onboarding",
        "/(auth)/login",
        "/(auth)/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/$workspaceSlug"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx"
    },
    "/_authenticated/$workspaceSlug": {
      "filePath": "_authenticated/$workspaceSlug",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/$workspaceSlug/_dashboard",
        "/_authenticated/$workspaceSlug/welcome"
      ]
    },
    "/_authenticated/$workspaceSlug/_dashboard": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard.tsx",
      "parent": "/_authenticated/$workspaceSlug",
      "children": [
        "/_authenticated/$workspaceSlug/_dashboard/getting-started",
        "/_authenticated/$workspaceSlug/_dashboard/",
        "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug",
        "/_authenticated/$workspaceSlug/_dashboard/projects/"
      ]
    },
    "/_authenticated/$workspaceSlug/welcome": {
      "filePath": "_authenticated/$workspaceSlug/welcome.tsx",
      "parent": "/_authenticated/$workspaceSlug"
    },
    "/_authenticated/$workspaceSlug/_dashboard/getting-started": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/getting-started.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard"
    },
    "/_authenticated/$workspaceSlug/_dashboard/": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/index.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard"
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard",
      "children": [
        "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities",
        "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare",
        "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people",
        "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/"
      ]
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/index.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard"
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/activities.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug"
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/compare.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug"
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/people.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug"
    },
    "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/": {
      "filePath": "_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug/index.tsx",
      "parent": "/_authenticated/$workspaceSlug/_dashboard/projects/$projectSlug"
    }
  }
}
ROUTE_MANIFEST_END */
