export interface Activity {
  id: string;
  user: {
    name: string;
    email: string;
    avatar: string;
  };
  event: string;
  platform: string;
  time: string;
  project: string;
  environment: string;
  timestamp: string;
  location: string;
  ip: string;
  children?: Activity[];
}

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "2",
    user: {
      name: "sarahsmith",
      email: "sarah.smith@company.com",
      avatar: "S",
    },
    event: "Environment Created",
    platform: "CLI",
    time: "2 days ago",
    project: "mobile-app",
    environment: "staging",
    timestamp: "Jan 05, 2025, 14:15:22",
    location: "San Francisco, US",
    ip: "192.168.1.100",
    children: [
      {
        id: "1",
        user: {
          name: "akinkunmioye42",
          email: "akinkunmioye42@gmail.com",
          avatar: "A",
        },
        event: "2 Secret(s) Pulled",
        platform: "APP",
        time: "1 day ago",
        project: "xing's-project",
        environment: "development",
        timestamp: "Jan 06, 2025, 18:27:42",
        location: "Not available",
        ip: "105.119.18.70",
      },
      {
        id: "3",
        user: {
          name: "davidchen",
          email: "david.chen@company.com",
          avatar: "D",
        },
        event: "5 Secret(s) Updated",
        platform: "WEB",
        time: "3 days ago",
        project: "backend-api",
        environment: "production",
        timestamp: "Jan 04, 2025, 09:45:11",
        location: "Singapore",
        ip: "172.16.0.100",
      },
      {
        id: "101",
        user: {
          name: "sarahsmith",
          email: "sarah.smith@company.com",
          avatar: "S",
        },
        event: "Environment Variables Added",
        platform: "CLI",
        time: "2 days ago",
        project: "mobile-app",
        environment: "staging",
        timestamp: "Jan 05, 2025, 14:20:55",
        location: "San Francisco, US",
        ip: "192.168.1.100",
      },
    ],
  },

  {
    id: "4",
    user: {
      name: "mariagomez",
      email: "maria.gomez@company.com",
      avatar: "M",
    },
    event: "Project Created",
    platform: "APP",
    time: "4 days ago",
    project: "data-pipeline",
    environment: "development",
    timestamp: "Jan 03, 2025, 16:33:45",
    location: "Madrid, Spain",
    ip: "10.0.0.50",
    children: [
      {
        id: "5",
        user: {
          name: "jameswilson",
          email: "james.wilson@company.com",
          avatar: "J",
        },
        event: "3 Secret(s) Deleted",
        platform: "CLI",
        time: "5 days ago",
        project: "frontend-app",
        environment: "staging",
        timestamp: "Jan 02, 2025, 11:22:33",
        location: "London, UK",
        ip: "192.168.2.200",
      },
      {
        id: "6",
        user: {
          name: "emilyjohnson",
          email: "emily.johnson@company.com",
          avatar: "E",
        },
        event: "Environment Deleted",
        platform: "WEB",
        time: "6 days ago",
        project: "analytics-service",
        environment: "production",
        timestamp: "Jan 01, 2025, 08:12:55",
        location: "Sydney, Australia",
        ip: "172.16.1.150",
      },
      {
        id: "102",
        user: {
          name: "mariagomez",
          email: "maria.gomez@company.com",
          avatar: "M",
        },
        event: "Team Permission Changed",
        platform: "APP",
        time: "4 days ago",
        project: "data-pipeline",
        environment: "development",
        timestamp: "Jan 03, 2025, 16:45:12",
        location: "Madrid, Spain",
        ip: "10.0.0.50",
      },
      {
        id: "103",
        user: {
          name: "tanjiro45",
          email: "tanjiro45@company.com",
          avatar: "T",
        },
        event: "4 Secret(s) Added",
        platform: "WEB",
        time: "4 days ago",
        project: "data-pipeline",
        environment: "development",
        timestamp: "Jan 03, 2025, 17:22:08",
        location: "Tokyo, Japan",
        ip: "198.51.123.45",
      },
    ],
  },

  {
    id: "7",
    user: {
      name: "alexanderkim",
      email: "alexander.kim@company.com",
      avatar: "A",
    },
    event: "Team Member Added",
    platform: "WEB",
    time: "1 week ago",
    project: "payment-gateway",
    environment: "all",
    timestamp: "Dec 28, 2024, 15:40:03",
    location: "Seoul, South Korea",
    ip: "203.0.113.25",
    children: [
      {
        id: "8",
        user: {
          name: "sophiawang",
          email: "sophia.wang@company.com",
          avatar: "S",
        },
        event: "Role Updated",
        platform: "WEB",
        time: "1 week ago",
        project: "payment-gateway",
        environment: "all",
        timestamp: "Dec 28, 2024, 15:45:22",
        location: "Seoul, South Korea",
        ip: "203.0.113.26",
      },
      {
        id: "104",
        user: {
          name: "alexanderkim",
          email: "alexander.kim@company.com",
          avatar: "A",
        },
        event: "API Key Created",
        platform: "WEB",
        time: "1 week ago",
        project: "payment-gateway",
        environment: "development",
        timestamp: "Dec 28, 2024, 16:05:17",
        location: "Seoul, South Korea",
        ip: "203.0.113.25",
      },
      {
        id: "105",
        user: {
          name: "sophiawang",
          email: "sophia.wang@company.com",
          avatar: "S",
        },
        event: "Integration Connected",
        platform: "APP",
        time: "1 week ago",
        project: "payment-gateway",
        environment: "staging",
        timestamp: "Dec 28, 2024, 17:30:44",
        location: "Seoul, South Korea",
        ip: "203.0.113.26",
      },
      {
        id: "106",
        user: {
          name: "alexanderkim",
          email: "alexander.kim@company.com",
          avatar: "A",
        },
        event: "Environment Template Applied",
        platform: "WEB",
        time: "1 week ago",
        project: "payment-gateway",
        environment: "production",
        timestamp: "Dec 29, 2024, 09:12:33",
        location: "Seoul, South Korea",
        ip: "203.0.113.25",
      },
    ],
  },

  {
    id: "9",
    user: {
      name: "rajeevpatel",
      email: "rajeev.patel@company.com",
      avatar: "R",
    },
    event: "10 Secret(s) Imported",
    platform: "CLI",
    time: "2 weeks ago",
    project: "auth-service",
    environment: "staging",
    timestamp: "Dec 21, 2024, 11:05:37",
    location: "Mumbai, India",
    ip: "192.0.2.100",
    children: [
      {
        id: "10",
        user: {
          name: "rajeevpatel",
          email: "rajeev.patel@company.com",
          avatar: "R",
        },
        event: "2 Secret(s) Rotated",
        platform: "CLI",
        time: "2 weeks ago",
        project: "auth-service",
        environment: "staging",
        timestamp: "Dec 21, 2024, 11:10:15",
        location: "Mumbai, India",
        ip: "192.0.2.100",
      },
      {
        id: "11",
        user: {
          name: "rajeevpatel",
          email: "rajeev.patel@company.com",
          avatar: "R",
        },
        event: "Environment Cloned",
        platform: "CLI",
        time: "2 weeks ago",
        project: "auth-service",
        environment: "production",
        timestamp: "Dec 21, 2024, 11:15:42",
        location: "Mumbai, India",
        ip: "192.0.2.100",
      },
      {
        id: "107",
        user: {
          name: "isabellakhan",
          email: "isabella.khan@company.com",
          avatar: "I",
        },
        event: "Secret Group Created",
        platform: "WEB",
        time: "2 weeks ago",
        project: "auth-service",
        environment: "staging",
        timestamp: "Dec 21, 2024, 13:45:10",
        location: "New Delhi, India",
        ip: "192.0.2.150",
      },
      {
        id: "108",
        user: {
          name: "rajeevpatel",
          email: "rajeev.patel@company.com",
          avatar: "R",
        },
        event: "Export Initiated",
        platform: "CLI",
        time: "2 weeks ago",
        project: "auth-service",
        environment: "development",
        timestamp: "Dec 22, 2024, 09:33:27",
        location: "Mumbai, India",
        ip: "192.0.2.100",
      },
      {
        id: "109",
        user: {
          name: "isabellakhan",
          email: "isabella.khan@company.com",
          avatar: "I",
        },
        event: "3 Secret(s) Downloaded",
        platform: "APP",
        time: "2 weeks ago",
        project: "auth-service",
        environment: "staging",
        timestamp: "Dec 22, 2024, 10:15:30",
        location: "New Delhi, India",
        ip: "192.0.2.150",
      },
    ],
  },

  {
    id: "12",
    user: {
      name: "oliviabrown",
      email: "olivia.brown@company.com",
      avatar: "O",
    },
    event: "Project Settings Updated",
    platform: "APP",
    time: "3 weeks ago",
    project: "ml-pipeline",
    environment: "all",
    timestamp: "Dec 14, 2024, 09:33:21",
    location: "Toronto, Canada",
    ip: "198.51.100.75",
    children: [
      {
        id: "110",
        user: {
          name: "oliviabrown",
          email: "olivia.brown@company.com",
          avatar: "O",
        },
        event: "Branch Created",
        platform: "APP",
        time: "3 weeks ago",
        project: "ml-pipeline",
        environment: "development",
        timestamp: "Dec 14, 2024, 09:40:55",
        location: "Toronto, Canada",
        ip: "198.51.100.75",
      },
      {
        id: "111",
        user: {
          name: "nathanwilliams",
          email: "nathan.williams@company.com",
          avatar: "N",
        },
        event: "8 Secret(s) Pushed",
        platform: "CLI",
        time: "3 weeks ago",
        project: "ml-pipeline",
        environment: "development",
        timestamp: "Dec 14, 2024, 11:20:33",
        location: "Vancouver, Canada",
        ip: "198.51.100.80",
      },
      {
        id: "112",
        user: {
          name: "oliviabrown",
          email: "olivia.brown@company.com",
          avatar: "O",
        },
        event: "Webhook Created",
        platform: "WEB",
        time: "3 weeks ago",
        project: "ml-pipeline",
        environment: "staging",
        timestamp: "Dec 14, 2024, 14:15:09",
        location: "Toronto, Canada",
        ip: "198.51.100.75",
      },
      {
        id: "113",
        user: {
          name: "nathanwilliams",
          email: "nathan.williams@company.com",
          avatar: "N",
        },
        event: "Pull Request Opened",
        platform: "WEB",
        time: "3 weeks ago",
        project: "ml-pipeline",
        environment: "development",
        timestamp: "Dec 15, 2024, 08:45:22",
        location: "Vancouver, Canada",
        ip: "198.51.100.80",
      },
    ],
  },

  {
    id: "13",
    user: {
      name: "lucasmartin",
      email: "lucas.martin@company.com",
      avatar: "L",
    },
    event: "Integration Disconnected",
    platform: "WEB",
    time: "1 month ago",
    project: "crm-tools",
    environment: "production",
    timestamp: "Dec 05, 2024, 16:20:15",
    location: "Paris, France",
    ip: "203.0.113.100",
    children: [
      {
        id: "114",
        user: {
          name: "lucasmartin",
          email: "lucas.martin@company.com",
          avatar: "L",
        },
        event: "Environment Synced",
        platform: "WEB",
        time: "1 month ago",
        project: "crm-tools",
        environment: "production",
        timestamp: "Dec 05, 2024, 16:25:30",
        location: "Paris, France",
        ip: "203.0.113.100",
      },
      {
        id: "115",
        user: {
          name: "elenarusso",
          email: "elena.russo@company.com",
          avatar: "E",
        },
        event: "API Key Rotated",
        platform: "APP",
        time: "1 month ago",
        project: "crm-tools",
        environment: "production",
        timestamp: "Dec 05, 2024, 17:05:12",
        location: "Rome, Italy",
        ip: "203.0.113.150",
      },
    ],
  },

  {
    id: "14",
    user: {
      name: "mikejohnson",
      email: "mike.johnson@company.com",
      avatar: "M",
    },
    event: "Project Deleted",
    platform: "WEB",
    time: "1 month ago",
    project: "legacy-app",
    environment: "all",
    timestamp: "Dec 01, 2024, 10:05:33",
    location: "Chicago, US",
    ip: "172.16.254.1",
    children: [
      {
        id: "116",
        user: {
          name: "mikejohnson",
          email: "mike.johnson@company.com",
          avatar: "M",
        },
        event: "All Environments Deleted",
        platform: "WEB",
        time: "1 month ago",
        project: "legacy-app",
        environment: "all",
        timestamp: "Dec 01, 2024, 10:00:15",
        location: "Chicago, US",
        ip: "172.16.254.1",
      },
      {
        id: "117",
        user: {
          name: "mikejohnson",
          email: "mike.johnson@company.com",
          avatar: "M",
        },
        event: "Team Removed",
        platform: "WEB",
        time: "1 month ago",
        project: "legacy-app",
        environment: "all",
        timestamp: "Dec 01, 2024, 09:55:42",
        location: "Chicago, US",
        ip: "172.16.254.1",
      },
      {
        id: "118",
        user: {
          name: "mikejohnson",
          email: "mike.johnson@company.com",
          avatar: "M",
        },
        event: "Project Backup Created",
        platform: "WEB",
        time: "1 month ago",
        project: "legacy-app",
        environment: "all",
        timestamp: "Dec 01, 2024, 09:50:22",
        location: "Chicago, US",
        ip: "172.16.254.1",
      },
    ],
  },

  {
    id: "15",
    user: {
      name: "hanayamada",
      email: "hana.yamada@company.com",
      avatar: "H",
    },
    event: "Organization Settings Changed",
    platform: "WEB",
    time: "2 months ago",
    project: "all",
    environment: "all",
    timestamp: "Nov 10, 2024, 13:20:45",
    location: "Tokyo, Japan",
    ip: "192.0.2.200",
    children: [
      {
        id: "119",
        user: {
          name: "hanayamada",
          email: "hana.yamada@company.com",
          avatar: "H",
        },
        event: "2FA Enforced",
        platform: "WEB",
        time: "2 months ago",
        project: "all",
        environment: "all",
        timestamp: "Nov 10, 2024, 13:25:10",
        location: "Tokyo, Japan",
        ip: "192.0.2.200",
      },
      {
        id: "120",
        user: {
          name: "hanayamada",
          email: "hana.yamada@company.com",
          avatar: "H",
        },
        event: "SSO Connection Updated",
        platform: "WEB",
        time: "2 months ago",
        project: "all",
        environment: "all",
        timestamp: "Nov 10, 2024, 13:30:55",
        location: "Tokyo, Japan",
        ip: "192.0.2.200",
      },
      {
        id: "121",
        user: {
          name: "hanayamada",
          email: "hana.yamada@company.com",
          avatar: "H",
        },
        event: "Audit Log Retention Changed",
        platform: "WEB",
        time: "2 months ago",
        project: "all",
        environment: "all",
        timestamp: "Nov 10, 2024, 13:35:22",
        location: "Tokyo, Japan",
        ip: "192.0.2.200",
      },
    ],
  },
];
